### ISSUE TITLE
Data set too big.

### ISSUE THREAD

**Issue by mads2014** [kartik-v/yii2-widget-typeahead#4]
Hi,

I am trying to use your plugin. However, I find that dataset is too big so the page cannot load up.
I have a city database of 101909 records. What I want is, if users type in, then suggest the matches which Typeahead does, however.

Can there be a way to optimize your plugin to load up that many records?

Here's how I use it...

<?= $form->field($addressModel, 'city_id')->widget(Typeahead::classname(), [
        'dataset' => [
            [
                'local' => ArrayHelper::map(MetaLocation::findAll(array('type'=>'CI')), 'id','local_name'),
                'limit' => 5
            ]
        ],
        'pluginOptions' => ['highlight' => true],
        'options' => ['placeholder' => 'Filter as you type ...']
]); ?>

**Comment by kartik-v** [comment]
Note that I don't own the plugin... the widget is based on Twitter Typeahead.js -- you would need to configure plugin options for your use case by reading the [Typeahead plugin documentation](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md). You can configure the plugin options in the widget using `pluginOptions`  - please read the widget documentation for all possible properties.

Check the [Typeahead plugin examples](https://twitter.github.io/typeahead.js/examples/) for use cases.

You can use the `pluginOptions['minLength']` property to force triggering the ajax query after certain characters are typed... for example you can set it to 3 to fire the ajax call only after 3 chars... you would need to also optimize your query to return the top 20 records or something instead of returning all matches. 

Summary -- you would need to code and fine tune your application based on what works best yourself (what i mentioned above are just some hints/guidance).

**Comment by mads2014** [comment]
Thanks @kartik-v. I found my answer here: http://demos.krajee.com/widget-details/typeahead#advanced-usage
I setup a prefetch/remote typeahead.

<?= $form->field($addressModel, 'city_id')->widget(Typeahead::classname(), [
        'dataset' => [
            [
                'prefetch' => Yii::getAlias('@web') . '/samples/countries.json',
                'remote' => BaseUrl::to(['location/citylist']) . '&q=%QUERY',
                'limit' => 10
            ]
        ],
        'pluginOptions' => ['highlight' => true, 'minLength' => '3'],
        'options' => ['placeholder' => 'Filter as you type ...']
    ]); ?>
